DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
fav_id SERIAL PRIMARY KEY NOT NULL,
is_fav BOOLEAN,
user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
item_id INTEGER REFERENCES items(id) ON DELETE CASCADE
);
