DROP TABLE IF EXISTS favourites CASCADE;
CREATE TABLE favourites (
fav_id SERIAL PRIMARY KEY NOT NULL,
user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
item_id INTEGER REFERENCES items(item_id) ON DELETE CASCADE
);
